Proposed changes to "Unit tests CMake and Travis refactoring"
SergioRAgostinho/pcl pull request #1
Opened 2017-01-04 15:00 UTC by MarcoFalke

I think it makes sense to run the tests with gcc and clang.

2017-01-04 15:00 UTC, MarcoFalke commented
Feel free to squash instead of a pull.

2017-01-08 07:40 UTC, SergioRAgostinho requested changes
Thanks for the fixes.

2017-01-08 07:40 UTC, SergioRAgostinho commented on .travis.yml
> +    - compiler: clang
Setting the compiler to clang is causing the tests all tests to segfault when they run. I have a gut feeling it's an issue with our dependencies being compiled with g++ and probably a different version of the std c++ lib. So I would suggest to leave this one as well to gcc.

2017-01-08 13:04 UTC, MarcoFalke commented on .travis.yml
> +    - compiler: clang
I think your gut feeling is right. All green now.

2017-01-08 21:37 UTC, SergioRAgostinho approved these changes

2017-01-08 21:47 UTC, merged